# Generated by Django 3.2.6 on 2021-08-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210804_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oredermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
